name: lit-html
description: 効率的で、表現力豊かで、拡張可能なJavaScript HTMLテンプレートライブラリ
markdown: kramdown
kramdown:
  parse_block_html: true
google_analytics: UA-131004707-1
collections:
  guide:
    output: true
    permalink: /:collection/:title
include:
  - "_*_.html"
  - "_*_.*.html"
exclude: 
  - README.md
  - node_modules
