name: lit-html
description: 効率的で、表現力豊かで、拡張可能なJavaScript HTMLテンプレートライブラリ
markdown: kramdown
kramdown:
  parse_block_html: true
google_analytics:
collections:
  guide:
    output: true
    permalink: /:collection/:title
include:
  - "_*_.html"
  - "_*_.*.html"
